[2024-09-28T15:38:29.129+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-28T15:38:29.140+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: MI_PRIMER_DAG.first_task manual__2024-09-28T15:38:23+00:00 [queued]>
[2024-09-28T15:38:29.147+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: MI_PRIMER_DAG.first_task manual__2024-09-28T15:38:23+00:00 [queued]>
[2024-09-28T15:38:29.148+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 5
[2024-09-28T15:38:29.156+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): first_task> on 2024-09-28 15:38:23+00:00
[2024-09-28T15:38:29.163+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=68) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-28T15:38:29.164+0000] {standard_task_runner.py:72} INFO - Started process 70 to run task
[2024-09-28T15:38:29.164+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'MI_PRIMER_DAG', 'first_task', 'manual__2024-09-28T15:38:23+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/MI_PRIMER_DAG.py', '--cfg-path', '/tmp/tmpna2wrbsk']
[2024-09-28T15:38:29.164+0000] {standard_task_runner.py:105} INFO - Job 55: Subtask first_task
[2024-09-28T15:38:29.201+0000] {task_command.py:467} INFO - Running <TaskInstance: MI_PRIMER_DAG.first_task manual__2024-09-28T15:38:23+00:00 [running]> on host 57692e5e4e10
[2024-09-28T15:38:29.260+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='MI_PRIMER_DAG' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-28T15:38:23+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-28T15:38:23+00:00'
[2024-09-28T15:38:29.261+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-28T15:38:29.261+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-28T15:38:29.262+0000] {logging_mixin.py:190} INFO - Current task name:first_task state:running start_date:2024-09-28 15:38:29.141551+00:00
[2024-09-28T15:38:29.262+0000] {logging_mixin.py:190} INFO - Dag name:MI_PRIMER_DAG and current dag run status:running
[2024-09-28T15:38:29.262+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-28T15:38:29.263+0000] {logging_mixin.py:190} INFO - {'conf': <***.configuration.AirflowConfigParser object at 0x7f4374ef0c80>, 'dag': <DAG: MI_PRIMER_DAG>, 'dag_run': <DagRun MI_PRIMER_DAG @ 2024-09-28 15:38:23+00:00: manual__2024-09-28T15:38:23+00:00, state:running, queued_at: 2024-09-28 15:38:26.966044+00:00. externally triggered: True>, 'data_interval_end': DateTime(2024, 9, 28, 9, 0, 0, tzinfo=Timezone('UTC')), 'data_interval_start': DateTime(2024, 9, 27, 9, 0, 0, tzinfo=Timezone('UTC')), 'outlet_events': <***.utils.context.OutletEventAccessors object at 0x7f4346c75be0>, 'ds': '2024-09-28', 'ds_nodash': '20240928', 'execution_date': <Proxy at 0x7f4347bb89c0 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f4346c7fce0>, 'execution_date', DateTime(2024, 9, 28, 15, 38, 23, tzinfo=Timezone('UTC')))>, 'expanded_ti_count': None, 'inlets': [], 'inlet_events': InletEventsAccessors(_inlets=[], _datasets={}, _dataset_aliases={}, _session=<sqlalchemy.orm.session.Session object at 0x7f4346c0d2e0>), 'logical_date': DateTime(2024, 9, 28, 15, 38, 23, tzinfo=Timezone('UTC')), 'macros': <module '***.macros' from '/home/***/.local/lib/python3.12/site-packages/***/macros/__init__.py'>, 'map_index_template': None, 'next_ds': <Proxy at 0x7f4346df7040 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f4346c7fce0>, 'next_ds', '2024-09-28')>, 'next_ds_nodash': <Proxy at 0x7f4346cefec0 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f4346c7fce0>, 'next_ds_nodash', '20240928')>, 'next_execution_date': <Proxy at 0x7f4346c57e40 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f4346c7fce0>, 'next_execution_date', DateTime(2024, 9, 28, 15, 38, 23, tzinfo=Timezone('UTC')))>, 'outlets': [], 'params': {'Manual': False}, 'prev_data_interval_start_success': DateTime(2024, 9, 27, 9, 0, 0, tzinfo=Timezone('UTC')), 'prev_data_interval_end_success': DateTime(2024, 9, 28, 9, 0, 0, tzinfo=Timezone('UTC')), 'prev_ds': <Proxy at 0x7f4346c5db40 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f4346c7fce0>, 'prev_ds', '2024-09-28')>, 'prev_ds_nodash': <Proxy at 0x7f4346c60a80 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f4346c7fce0>, 'prev_ds_nodash', '20240928')>, 'prev_execution_date': <Proxy at 0x7f4346cbd080 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f4346c7fce0>, 'prev_execution_date', DateTime(2024, 9, 28, 15, 38, 23, tzinfo=Timezone('UTC')))>, 'prev_execution_date_success': <Proxy at 0x7f4346fd96c0 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f4346c7fce0>, 'prev_execution_date_success', DateTime(2024, 9, 28, 15, 28, 22, tzinfo=Timezone('UTC')))>, 'prev_start_date_success': DateTime(2024, 9, 28, 15, 28, 26, 468434, tzinfo=Timezone('UTC')), 'prev_end_date_success': DateTime(2024, 9, 28, 15, 28, 30, 482467, tzinfo=Timezone('UTC')), 'run_id': 'manual__2024-09-28T15:38:23+00:00', 'task': <Task(PythonOperator): first_task>, 'task_instance': <TaskInstance: MI_PRIMER_DAG.first_task manual__2024-09-28T15:38:23+00:00 [running]>, 'task_instance_key_str': 'MI_PRIMER_DAG__first_task__20240928', 'test_mode': False, 'ti': <TaskInstance: MI_PRIMER_DAG.first_task manual__2024-09-28T15:38:23+00:00 [running]>, 'tomorrow_ds': <Proxy at 0x7f4346c88ec0 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f4346c7fce0>, 'tomorrow_ds', '2024-09-29')>, 'tomorrow_ds_nodash': <Proxy at 0x7f4346c88b00 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f4346c7fce0>, 'tomorrow_ds_nodash', '20240929')>, 'triggering_dataset_events': <Proxy at 0x7f4346c8bc80 with factory <function _get_template_context.<locals>.get_triggering_events at 0x7f4346c7d760>>, 'ts': '2024-09-28T15:38:23+00:00', 'ts_nodash': '20240928T153823', 'ts_nodash_with_tz': '20240928T153823+0000', 'var': {'json': None, 'value': None}, 'conn': None, 'yesterday_ds': <Proxy at 0x7f4346c89840 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f4346c7fce0>, 'yesterday_ds', '2024-09-27')>, 'yesterday_ds_nodash': <Proxy at 0x7f4346c88880 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f4346c7fce0>, 'yesterday_ds_nodash', '20240927')>, 'templates_dict': None}
[2024-09-28T15:38:29.264+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/MI_PRIMER_DAG.py", line 26, in execute_task
    params = kwargs.get['params', {}]
             ~~~~~~~~~~^^^^^^^^^^^^^^
TypeError: 'builtin_function_or_method' object is not subscriptable
[2024-09-28T15:38:29.275+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-28T15:38:29.276+0000] {logging_mixin.py:190} INFO - Task start:2024-09-28 15:38:29.141551+00:00 end:2024-09-28 15:38:29.275427+00:00 duration:0.133876
[2024-09-28T15:38:29.276+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): first_task> dag:<DAG: MI_PRIMER_DAG> dagrun:<DagRun MI_PRIMER_DAG @ 2024-09-28 15:38:23+00:00: manual__2024-09-28T15:38:23+00:00, state:running, queued_at: 2024-09-28 15:38:26.966044+00:00. externally triggered: True>
[2024-09-28T15:38:29.276+0000] {logging_mixin.py:190} INFO - Failure caused by 'builtin_function_or_method' object is not subscriptable
[2024-09-28T15:38:29.277+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=MI_PRIMER_DAG, task_id=first_task, run_id=manual__2024-09-28T15:38:23+00:00, execution_date=20240928T153823, start_date=20240928T153829, end_date=20240928T153829
[2024-09-28T15:38:29.290+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-28T15:38:29.290+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 55 for task first_task ('builtin_function_or_method' object is not subscriptable; 70)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/MI_PRIMER_DAG.py", line 26, in execute_task
    params = kwargs.get['params', {}]
             ~~~~~~~~~~^^^^^^^^^^^^^^
TypeError: 'builtin_function_or_method' object is not subscriptable
[2024-09-28T15:38:29.338+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-28T15:38:29.355+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-28T15:38:29.357+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
